name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project with Maven
        run: mvn -B package --file pom.xml
  publish-job:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: github
          server-username: GITHUB_USER_REF  # env variable name for username
          server-password: GITHUB_TOKEN_REF
      - run: mvn clean install deploy -DskipTests
        env:
          GITHUB_USER_REF: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GITHUB_TOKEN }}
